import { bilingualQuestions } from "./bilingualQuestions";

export type Question = { id: number; category: number; text: string; textTl?: string; wisdom?: string; wisdomTl?: string; custom?: boolean };

export const categories = [["Identity & Self-Perception","Identity"],["Vulnerability & Growth","Vulnerability"],["Relationships & Connection","Connection"],["Meaning & Purpose","Purpose"],["Time, Mortality & Perspective","Perspective"],["Emotional Intelligence & Reactions","Emotions"],["Worldview & Deep Beliefs","Worldview"],["Life Transitions & Reflections","Transitions"],["Self-Discovery & Future","Future"],["Connection, Gratitude & Group Reflection","Together"]] as const;

export const questions: Question[] = [
  { id: 1, category: 0, text: "Who are you when no one is watching?" },
  { id: 2, category: 0, text: "What is one thing you wish people understood about you?" },
  { id: 3, category: 0, text: "What part of yourself do you feel you hide the most?" },
  { id: 4, category: 0, text: "When do you feel most like your authentic self?" },
  { id: 5, category: 0, text: "What is a belief you hold that not many people know about?" },
  { id: 6, category: 0, text: "What is the biggest lie you've told yourself?" },
  { id: 7, category: 0, text: "What are you most afraid people will find out about you?" },
  { id: 8, category: 0, text: "When did you last feel truly seen?" },
  { id: 9, category: 0, text: "What does your inner voice sound like? Is it kind?" },
  { id: 10, category: 0, text: "If you stripped away your job, hobbies, and relationships—who is left?" },
  { id: 11, category: 0, text: "What is the most honest thing you can say about yourself right now?" },
  { id: 12, category: 0, text: "What role do you play in your own life—main character, sidekick, or observer?" },
  { id: 13, category: 0, text: "What is a label you've accepted that doesn't really fit you?" },
  { id: 14, category: 0, text: "When do you feel most disconnected from yourself?" },
  { id: 15, category: 0, text: "What is one thing you know about yourself that no one else could guess?" },
  { id: 16, category: 0, text: "What does your \"shadow self\" look like?" },
  { id: 17, category: 0, text: "What is a contradiction about you that you've made peace with?" },
  { id: 18, category: 0, text: "If your life was a book, what would the current chapter be titled?" },
  { id: 19, category: 0, text: "What is the bravest thing about you?" },
  { id: 20, category: 0, text: "What is something you love about yourself that took time to love?" },
  { id: 21, category: 1, text: "What is a mistake that changed you forever?" },
  { id: 22, category: 1, text: "What is a wound you're still healing from?" },
  { id: 23, category: 1, text: "What is something you've never told anyone but wish you could?" },
  { id: 24, category: 1, text: "What is the hardest thing you've ever had to forgive?" },
  { id: 25, category: 1, text: "What part of your past are you most ashamed of?" },
  { id: 26, category: 1, text: "When was the last time you cried? What was it about?" },
  { id: 27, category: 1, text: "What keeps you up at night?" },
  { id: 28, category: 1, text: "What is a fear you've conquered, and one you're still facing?" },
  { id: 29, category: 1, text: "What do you do when you feel invisible or unheard?" },
  { id: 30, category: 1, text: "What is the most vulnerable you've ever been with another person?" },
  { id: 31, category: 1, text: "What is the most humbling experience of your life?" },
  { id: 32, category: 1, text: "What is a wound you're still afraid to touch?" },
  { id: 33, category: 1, text: "What is the most honest apology you've ever given?" },
  { id: 34, category: 1, text: "What is something you've forgiven but not forgotten?" },
  { id: 35, category: 1, text: "When was the last time you felt truly helpless? What did you learn?" },
  { id: 36, category: 1, text: "What is a failure that redefined your path?" },
  { id: 37, category: 1, text: "What emotion do you run from the most?" },
  { id: 38, category: 1, text: "What is a scar (literal or metaphorical) that tells a story?" },
  { id: 39, category: 1, text: "What is the most difficult truth you've had to speak?" },
  { id: 40, category: 1, text: "What would it take for you to feel \"enough\"?" },
  { id: 41, category: 2, text: "What does love mean to you beyond romance?" },
  { id: 42, category: 2, text: "Who in your life do you feel you can be completely honest with?" },
  { id: 43, category: 2, text: "What is the most important thing you've learned from a friendship?" },
  { id: 44, category: 2, text: "What is a relationship you wish you had handled differently?" },
  { id: 45, category: 2, text: "How do you push people away? Why?" },
  { id: 46, category: 2, text: "What is something you need more of from the people around you?" },
  { id: 47, category: 2, text: "Who has shaped you the most, and do they know?" },
  { id: 48, category: 2, text: "How do you show love, and how do you prefer to receive it?" },
  { id: 49, category: 2, text: "What is your biggest relationship regret?" },
  { id: 50, category: 2, text: "What does it mean to you to be a good friend?" },
  { id: 51, category: 2, text: "What is the most unspoken thing between you and someone you love?" },
  { id: 52, category: 2, text: "What is the greatest lesson a lover taught you?" },
  { id: 53, category: 2, text: "What does emotional safety feel like to you?" },
  { id: 54, category: 2, text: "Who in your life do you feel you can't fully be yourself around? Why?" },
  { id: 55, category: 2, text: "What is a promise you made to someone that you still keep?" },
  { id: 56, category: 2, text: "What is a relationship that broke you, and one that rebuilt you?" },
  { id: 57, category: 2, text: "What do you most fear losing in a relationship?" },
  { id: 58, category: 2, text: "What is one thing you wish your family understood about you?" },
  { id: 59, category: 2, text: "How do you know when someone truly loves you?" },
  { id: 60, category: 2, text: "What is the most selfless thing someone has done for you?" },
  { id: 61, category: 3, text: "What do you think your life is trying to teach you right now?" },
  { id: 62, category: 3, text: "What is the most meaningful thing you've done with your time?" },
  { id: 63, category: 3, text: "What is something you want your life to be remembered for?" },
  { id: 64, category: 3, text: "What does a \"life well-lived\" look like to you?" },
  { id: 65, category: 3, text: "What is your soul's quietest desire?" },
  { id: 66, category: 3, text: "What is something you are deeply committed to?" },
  { id: 67, category: 3, text: "What gives your life meaning on the hardest days?" },
  { id: 68, category: 3, text: "What would you do if you knew you couldn't fail?" },
  { id: 69, category: 3, text: "What is something you feel called to do, but haven't yet?" },
  { id: 70, category: 3, text: "What legacy do you want to leave behind?" },
  { id: 71, category: 3, text: "What is a cause or issue that makes you angrier than it should?" },
  { id: 72, category: 3, text: "What is a moment you felt you were exactly where you were supposed to be?" },
  { id: 73, category: 3, text: "What is a question you'd ask the universe if you could?" },
  { id: 74, category: 3, text: "What does it mean to you to leave a mark?" },
  { id: 75, category: 3, text: "What is the most spiritual experience you've had?" },
  { id: 76, category: 3, text: "What is a mundane activity that feels sacred to you?" },
  { id: 77, category: 3, text: "What is one thing you would die for?" },
  { id: 78, category: 3, text: "What is one thing you would live for?" },
  { id: 79, category: 3, text: "What is the purpose of pain, in your view?" },
  { id: 80, category: 3, text: "What gives you hope when everything feels bleak?" },
  { id: 81, category: 4, text: "If you died tomorrow, what would you regret not saying?" },
  { id: 82, category: 4, text: "What do you think happens when we die?" },
  { id: 83, category: 4, text: "What would you do if you knew you only had one year to live?" },
  { id: 84, category: 4, text: "What is the most important thing to do with the time you have?" },
  { id: 85, category: 4, text: "What is a memory you want to hold onto forever?" },
  { id: 86, category: 4, text: "What is something you're holding onto that you need to let go of?" },
  { id: 87, category: 4, text: "If you could go back, what would you tell your younger self?" },
  { id: 88, category: 4, text: "What do you think your older self will wish you had done?" },
  { id: 89, category: 4, text: "When did you last feel truly alive?" },
  { id: 90, category: 4, text: "What is the most beautiful thing about being human, to you?" },
  { id: 91, category: 4, text: "What is a memory that haunts you, and one that heals you?" },
  { id: 92, category: 4, text: "What is the most urgent thing on your mind right now?" },
  { id: 93, category: 4, text: "What is a moment of beauty you've witnessed that stopped you in your tracks?" },
  { id: 94, category: 4, text: "If you could write a letter to your future self, what would it say?" },
  { id: 95, category: 4, text: "What is something you've wasted too much time on?" },
  { id: 96, category: 4, text: "What is one thing you want to do before you die that surprises people?" },
  { id: 97, category: 4, text: "What does \"forever\" mean to you?" },
  { id: 98, category: 4, text: "What would you want your last words to be?" },
  { id: 99, category: 4, text: "What is a moment of silence that spoke louder than words?" },
  { id: 100, category: 4, text: "What is the most timeless part of you?" },
  { id: 101, category: 5, text: "How do you typically react when you're triggered or upset?" },
  { id: 102, category: 5, text: "What is your biggest emotional weakness?" },
  { id: 103, category: 5, text: "What emotion do you struggle to express the most?" },
  { id: 104, category: 5, text: "What do you do when you feel overwhelmed?" },
  { id: 105, category: 5, text: "What is a story you've told yourself that isn't true?" },
  { id: 106, category: 5, text: "How do you cope with loneliness?" },
  { id: 107, category: 5, text: "What role does anger play in your life?" },
  { id: 108, category: 5, text: "What is something you need to forgive yourself for?" },
  { id: 109, category: 5, text: "What does peace feel like to you?" },
  { id: 110, category: 5, text: "How do you want to feel at the end of this year?" },
  { id: 111, category: 5, text: "What is a feeling you're carrying right now that you haven't named?" },
  { id: 112, category: 5, text: "What do you do when your heart and head disagree?" },
  { id: 113, category: 5, text: "What is a situation that always brings out the worst in you?" },
  { id: 114, category: 5, text: "What is a situation that always brings out the best in you?" },
  { id: 115, category: 5, text: "What is the most patient version of you? When does she/he show up?" },
  { id: 116, category: 5, text: "What is the most impatient version of you? What triggers them?" },
  { id: 117, category: 5, text: "What does \"taking care of yourself\" actually look like for you?" },
  { id: 118, category: 5, text: "When was the last time you were surprised by your own reaction?" },
  { id: 119, category: 5, text: "What is a feeling you miss feeling?" },
  { id: 120, category: 5, text: "What is a feeling you're tired of feeling?" },
  { id: 121, category: 6, text: "Do you believe people are inherently good? Why?" },
  { id: 122, category: 6, text: "What is something you've changed your mind about?" },
  { id: 123, category: 6, text: "What is a question you've never been able to answer?" },
  { id: 124, category: 6, text: "What do you think is the biggest problem in the world today?" },
  { id: 125, category: 6, text: "Do you believe everything happens for a reason?" },
  { id: 126, category: 6, text: "What is a truth you've had to accept that was hard?" },
  { id: 127, category: 6, text: "What does spirituality mean to you?" },
  { id: 128, category: 6, text: "What is something the world needs more of?" },
  { id: 129, category: 6, text: "What is a mystery you think will never be solved?" },
  { id: 130, category: 6, text: "What do you think is the root of human suffering?" },
  { id: 131, category: 6, text: "What is a belief you hold that is unpopular or controversial?" },
  { id: 132, category: 6, text: "Do you believe in second chances? Third? Infinite?" },
  { id: 133, category: 6, text: "What is the most important question philosophy has yet to answer?" },
  { id: 134, category: 6, text: "What does justice mean to you?" },
  { id: 135, category: 6, text: "Is there such a thing as a \"good\" person and a \"bad\" person?" },
  { id: 136, category: 6, text: "What is the role of suffering in human life?" },
  { id: 137, category: 6, text: "Do we have free will, or is everything determined?" },
  { id: 138, category: 6, text: "What is a truth you find comforting?" },
  { id: 139, category: 6, text: "What is a truth you find terrifying?" },
  { id: 140, category: 6, text: "What is something you're certain about, and something you're uncertain about?" },
  { id: 141, category: 7, text: "What chapter of your life just ended?" },
  { id: 142, category: 7, text: "What chapter are you in right now?" },
  { id: 143, category: 7, text: "What is a loss that changed your trajectory?" },
  { id: 144, category: 7, text: "What was a turning point in your life?" },
  { id: 145, category: 7, text: "When did you feel you finally \"grew up\"?" },
  { id: 146, category: 7, text: "What is a phase of your life you miss?" },
  { id: 147, category: 7, text: "What is something you're ready to release or leave behind?" },
  { id: 148, category: 7, text: "What is a new beginning you're scared of?" },
  { id: 149, category: 7, text: "What is a change you're resisting, but need to embrace?" },
  { id: 150, category: 7, text: "What is a moment of grace or luck that changed everything?" },
  { id: 151, category: 7, text: "What is a door that closed that you're grateful for?" },
  { id: 152, category: 7, text: "What is a door that opened that you didn't expect?" },
  { id: 153, category: 7, text: "What is a year of your life you'd relive, and one you'd skip?" },
  { id: 154, category: 7, text: "What is a version of yourself you've outgrown?" },
  { id: 155, category: 7, text: "What is a version of yourself you're still trying to become?" },
  { id: 156, category: 7, text: "What is the biggest shift in perspective you've had?" },
  { id: 157, category: 7, text: "What is a goodbye that still stings?" },
  { id: 158, category: 7, text: "What is a hello that changed everything?" },
  { id: 159, category: 7, text: "What is a transition you're currently in the middle of?" },
  { id: 160, category: 7, text: "What is the most important thing you've learned from change?" },
  { id: 161, category: 8, text: "What do you need right now, even if you don't know how to ask for it?" },
  { id: 162, category: 8, text: "What is something you've been avoiding?" },
  { id: 163, category: 8, text: "If you could break one rule, which would it be?" },
  { id: 164, category: 8, text: "What would you do if you weren't afraid?" },
  { id: 165, category: 8, text: "What do you need less of in your life?" },
  { id: 166, category: 8, text: "What do you need more of?" },
  { id: 167, category: 8, text: "What is a dream you've given up on?" },
  { id: 168, category: 8, text: "What is a small step you could take today toward a happier life?" },
  { id: 169, category: 8, text: "What is your soul's deepest question right now?" },
  { id: 170, category: 8, text: "What are you hoping this conversation will help you understand?" },
  { id: 171, category: 8, text: "What is a dream you're afraid to say out loud?" },
  { id: 172, category: 8, text: "What is a limitation you've placed on yourself?" },
  { id: 173, category: 8, text: "What would you do with total freedom, no consequences?" },
  { id: 174, category: 8, text: "What is a piece of yourself you're ready to reclaim?" },
  { id: 175, category: 8, text: "What is a habit you want to break, and one you want to build?" },
  { id: 176, category: 8, text: "What is the most courageous thing you could do tomorrow?" },
  { id: 177, category: 8, text: "What is the kindest thing you could do for yourself today?" },
  { id: 178, category: 8, text: "What is a question you're avoiding asking yourself?" },
  { id: 179, category: 8, text: "What is an answer you already know, but aren't ready to accept?" },
  { id: 180, category: 8, text: "What does your best possible future look like in five years?" },
  { id: 181, category: 9, text: "What is something you admire about each person in this group?" },
  { id: 182, category: 9, text: "What is something you wish this group knew about you?" },
  { id: 183, category: 9, text: "What is a shared experience that bonded us together?" },
  { id: 184, category: 9, text: "How can we support each other better?" },
  { id: 185, category: 9, text: "What is a conversation you wish we had sooner?" },
  { id: 186, category: 9, text: "What is something you want to create or build with this group?" },
  { id: 187, category: 9, text: "What does this friendship mean to you?" },
  { id: 188, category: 9, text: "What is one thing you'd like to remember from this conversation?" },
  { id: 189, category: 9, text: "What is your intention for our friendship going forward?" },
  { id: 190, category: 9, text: "What is one thing you're grateful for, right now, in this moment?" },
  { id: 191, category: 9, text: "What is a way this group has challenged you?" },
  { id: 192, category: 9, text: "What is a way this group has comforted you?" },
  { id: 193, category: 9, text: "What is something you've learned about yourself through these friendships?" },
  { id: 194, category: 9, text: "What is a shared silence that was meaningful?" },
  { id: 195, category: 9, text: "What is a shared laugh that you'll always remember?" },
  { id: 196, category: 9, text: "What is a difficult conversation you're glad we had?" },
  { id: 197, category: 9, text: "What is something you're scared to ask this group for?" },
  { id: 198, category: 9, text: "What is something you want to celebrate with this group?" },
  { id: 199, category: 9, text: "What is one word you'd like to embody in this group?" },
  { id: 200, category: 9, text: "What is your hope for this group in the next year?" },
  ...bilingualQuestions,
];
